

export const columns = [
  { name: "NAME", uid: "name" },
  { name: "ROLE", uid: "role" },
  { name: "ADDRESS", uid: "address" },
  { name: "BIRTHDAY", uid: "birthday" },
  { name: "ACTIONS", uid: "actions" },
]
export const roleColumns = [
  { name: "ROLE", uid: "test" },
]

export const menuItems = [
  { key: "new", name: "New File" },
  { key: "copy", name: "Copy Link" },
  { key: "edit", name: "Edit File" },
  { key: "delete", name: "Delete File" },
]

export const roles = [
  {
    role_name: "CEO",
  },
  {
    role_name: "Tester",
  },
  {
    role_name: "Developer",
  },
  {
    role_name: "UX Writer",
  },
]
export const users = [
  {
    id: 1,
    name: "Tony Reichert",
    role: "CEO",
    address: "active",
    birthday: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    role: "Technical Lead",
    address: "paused",
    birthday: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    role: "Senior Developer",
    address: "active",
    birthday: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    role: "Community Manbirthdayr",
    address: "vacation",
    birthday: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    role: "Sales Manbirthdayr",
    address: "active",
    birthday: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Tony Reichert",
    role: "CEO",
    address: "active",
    birthday: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 10,
    name: "Kristen Copper",
    role: "Sales Manbirthdayr",
    address: "active",
    birthday: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 8,
    name: "Jane Fisher",
    role: "Senior Developer",
    address: "active",
    birthday: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 7,
    name: "Zoey Lang",
    role: "Technical Lead",
    address: "paused",
    birthday: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },

  {
    id: 9,
    name: "William Howard",
    role: "Community Manbirthdayr",
    address: "vacation",
    birthday: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 11,
    name: "Tony Reichert",
    role: "CEO",
    address: "active",
    birthday: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 12,
    name: "Kristen Copper",
    role: "Sales Manbirthdayr",
    address: "active",
    birthday: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 13,
    name: "Jane Fisher",
    role: "Senior Developer",
    address: "active",
    birthday: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 14,
    name: "Zoey Lang",
    role: "Technical Lead",
    address: "paused",
    birthday: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 15,
    name: "Tony Reichert",
    role: "CEO",
    address: "active",
    birthday: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 16,
    name: "Kristen Copper",
    role: "Sales Manbirthdayr",
    address: "active",
    birthday: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
]
